### PR TITLE
Disable prefer default export

### PR DESCRIPTION
**Pull request by orloxx**
Let's add new rules here as we see fit

### CODE REVIEW

**Comment by cesalazar** [comment]
Can we consider keeping named exports? At least for the code, I know defaults are necessary for Next pages.

Having the export named prevents (of course there's a way to mess with it, using `as`) the imports being named randomly.

`import todayIFeltEdgy from 'atoms'` 🙄 🤦🏽‍♂️

 Then do a search in the project trying to find what was imported.

**Comment by orloxx** [comment]
This lets us precisely do that. I'm turning off the default export as a rule

**Comment by cesalazar** [comment]
Aaaand im realizing that's exactly what that rules does. I'm the sharpest knife.

**Review by cesalazar — APPROVED** [review]
👌🏽

**Pull request merged**
